package com.code.enums;

public enum SecurityAnalysisClassesEnum {
	
	EQUIPMENT_TYPES("EQUIPMENT_TYPES"),
	DATA_SOURCES("DATA_SOURCES"),
	FOLLOW_RESULTS("FOLLOW_RESULTS"),
	CASES_TYPES("CASES_TYPES"),
	EXTERNAL_SIDES("EXTERNAL_SIDES"),
	EXTERNAL_REGIONS("EXTERNAL_REGIONS"),
	NETWORK_ROLES("NETWORK_ROLES"),
	REFERRAL_TYPE("REFERRAL_TYPE"),
	GUIDANCE_TYPES("GUIDANCE_TYPES"),
	CHAT_ACTIONS("CHAT_ACTIONS"),
	STOP_REASONS("STOP_REASONS"),
	TRANS_TYPES("TRANS_TYPES"),
	MONTR_REASONS("MONTR_REASONS"),
	;
	private String code;

	private SecurityAnalysisClassesEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}

