package com.code.enums;

public enum EntitySequenceGeneratorEnum {
	INFO(1L),
	CAR_RENTAL(2L),
	SECURITY_CHECK(3L),
	ASSIGNMENT_EMPLOYEE(4L),
	AGENT_CODE(5L),
	SECURITY_GUARD_MISSION(6L),
	ASSIGNMENT_NON_EMPLOYEE(7L),
	SUPPORT_FINANCE_ACCOUNTS(8L),
	FIN_DEP_SUPPORT(9L),
	MONTHLY_REWARD(10L),
	INFO_REWARD(11L),
	PENALTY_ARREST(12L),
	LAB_CHECK(13L),
	REFERENCE_NUMBER(14L),
	INFO_DIRECTORATE(15L),
	INFO_ALMADINA_REGION(16L),
	INFO_ASEER_REGION(17L),
	INFO_EASTERN_REGION_(18L),
	INFO_GAZAN_REGION(19L),
	INFO_GOUF_REGION(20L),
	INFO_MAKA_ELMOKRAMA(21L),
	INFO_NAGRAN_REGION(22L),
	INFO_NORTH_BORDER_REGION(23L),
	INFO_TABOK_REGION(24L),
	INFO_ACADEMY_REGION(25L),
	NETWORK_NUMBER(26L),
	;

	private Long entityId;

	private EntitySequenceGeneratorEnum(Long entityId) {
		this.entityId = entityId;
	}

	public Long getEntityId() {
		return entityId;
	}
}
