
package com.code.integration.promotionsdrugstest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.code.services.config.InfoSysConfigurationService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PromotionsDrugsTestWSService", targetNamespace = "http://integration.code.com/promotionsDrugsTest", wsdlLocation = "http://192.168.168.121:7002/ETRServicesPromotionsDrugs/PromotionsDrugsTestWS?WSDL")
public class PromotionsDrugsTestWSService extends Service {

	private final static URL PROMOTIONSDRUGSTESTWSSERVICE_WSDL_LOCATION;
	private final static WebServiceException PROMOTIONSDRUGSTESTWSSERVICE_EXCEPTION;
	private final static QName PROMOTIONSDRUGSTESTWSSERVICE_QNAME = new QName("http://integration.code.com/promotionsDrugsTest", "PromotionsDrugsTestWSService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(InfoSysConfigurationService.getHCMSoapUrl());
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		PROMOTIONSDRUGSTESTWSSERVICE_WSDL_LOCATION = url;
		PROMOTIONSDRUGSTESTWSSERVICE_EXCEPTION = e;
	}

	public PromotionsDrugsTestWSService() {
		super(__getWsdlLocation(), PROMOTIONSDRUGSTESTWSSERVICE_QNAME);
	}

	public PromotionsDrugsTestWSService(WebServiceFeature... features) {
		super(__getWsdlLocation(), PROMOTIONSDRUGSTESTWSSERVICE_QNAME, features);
	}

	public PromotionsDrugsTestWSService(URL wsdlLocation) {
		super(wsdlLocation, PROMOTIONSDRUGSTESTWSSERVICE_QNAME);
	}

	public PromotionsDrugsTestWSService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, PROMOTIONSDRUGSTESTWSSERVICE_QNAME, features);
	}

	public PromotionsDrugsTestWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PromotionsDrugsTestWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns PromotionsDrugsTestWS
	 */
	@WebEndpoint(name = "PromotionsDrugsTestWSHttpPort")
	public PromotionsDrugsTestWS getPromotionsDrugsTestWSHttpPort() {
		return super.getPort(new QName("http://integration.code.com/promotionsDrugsTest", "PromotionsDrugsTestWSHttpPort"), PromotionsDrugsTestWS.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default values.
	 * @return returns PromotionsDrugsTestWS
	 */
	@WebEndpoint(name = "PromotionsDrugsTestWSHttpPort")
	public PromotionsDrugsTestWS getPromotionsDrugsTestWSHttpPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://integration.code.com/promotionsDrugsTest", "PromotionsDrugsTestWSHttpPort"), PromotionsDrugsTestWS.class, features);
	}

	private static URL __getWsdlLocation() {
		if (PROMOTIONSDRUGSTESTWSSERVICE_EXCEPTION != null) {
			throw PROMOTIONSDRUGSTESTWSSERVICE_EXCEPTION;
		}
		return PROMOTIONSDRUGSTESTWSSERVICE_WSDL_LOCATION;
	}

}
