package com.code.enums;

public enum ClassesEnum {
	ASSIGNMENT_REASONS("ASSIGNMENT_REASONS"),
	SURVEILLANCE_REASONS("SURVEILLANCE_REASONS"),
	SURVEILLANCE_BEHAVIOURAL_EVALUATION_POINT("SURVEILLANCE_BEHAVIOURAL_EVALUATION_POINT"),
	SURVEILLANCE_FUNCTIONAL_EVALUATION_POINT("SURVEILLANCE_FUNCTIONAL_EVALUATION_POINT"),
	ASSIGNMENT_INFO_EVALUATION("ASSIGNMENT_INFO_EVALUATION"),
	ASSIGNMENT_ATTENDANCE_EVALUATION("ASSIGNMENT_ATTENDANCE_EVALUATION"),
	ASSIGNMENT_PERSONAL_EVALUATION("ASSIGNMENT_PERSONAL_EVALUATION"),
	ASSIGNMENT_END_REASONS("ASSIGNMENT_END_REASONS"),
	CAR_MODELS("CAR_MODELS"),
	CAR_COMPANIES("CAR_COMPANIES"),
	INCOMING_SIDES("INCOMING_SIDES"),
	DEALING_TYPES("DEALING_TYPES"),
	DEALING_LEVELS("DEALING_LEVELS"),
	NOTE_SIDES("NOTE_SIDES"),
	SECURITY_SECTIONS("SECURITY_SECTIONS"),
	ANALYSIS_REFERENCE("ANALYSIS_REFERENCE"),
	MISSION_TYPES("MISSION_TYPES"),
	WEAPON_TYPES("WEAPON_TYPES"),
	EQUIPMENT_TYPES("EQUIPMENT_TYPES"),
	HEALTH_CARE_CANTERS("HEALTH_CARE_CANTERS"),
	LAB_CHECK_MISSIONS("LAB_CHECK_MISSIONS"),
	MATERIAL_TYPES("MATERIAL_TYPES"),
	ORDER_SOURCES("ORDER_SOURCES"),
	ORGNAIZATIONS_AND_ISSUES("ORGNAIZATIONS_AND_ISSUES"),
	FISHING("FISHING"),
	INFO_EVALUATION("INFO_EVALUATION"),
	EMP_SEC_SURV_RESON("EMP_SEC_SURV_RESON"),
	NONEMP_SEC_SURV_RESON("NONEMP_SEC_SURV_RESON"),
	INFO_PRIORITY("INFO_PRIORITY"),
	INFO_CONFIDENTIALITY("INFO_CONFIDENTIALITY")
	;

	private String code;

	private ClassesEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
