
package com.code.enums;

public enum QueryNamesEnum {
    
    HIJRI_CALENDER_GET_HIJRI_CALENDAR("hijriCalendar_getHijriCalendar"),
    HIJRI_CALENDER_GET_GREG_DATES("hijriCalendar_getGregDates"),
    /******************************************************************************************************************/
    ASSIGNMENT_AGENT_CLASS_SEARCH_AGENT_CLASSES("assignmentAgentClass_searchAgentClasses"),
    /******************************************************************************************************************/
    ASSIGNMENT_DATA_SEARCH_ASSIGNMENTS("assignmentData_searchAssignments"),
    /******************************************************************************************************************/
    ASSIGNMENT_DETAIL_DATA_SEARCH_INFO_ASSIGNMENT_DETAILS_DATA("assignmentDetailData_searchInfoAssignmentDetailsData"),
    ASSIGNMENT_DETAIL_DATA_SEARCH_LAST_ASSIGNMENT_DETAILS_DATA("assignmentDetailData_searchLastAssignmentDetailsData"),
    ASSIGNMENT_DETAILS_DATA_SEARCH_ASSIGNMENT_DETAILS_DATA("assignmentDetailData_searchAssignmentDetailsData"),
    ASSIGNMENT_DETAILS_DATA_SUM_MONTHLY_REWARD("assignmentDetailData_sumMonthlyReward"),
    ASSIGNMENT_DETAILS_DATA_SEARCH_ACTIVE_ASSIGNMENT_DETAIL_DATE("assignmentDetailData_searchActiveAssignmentDetailData"),
    ASSIGNMENT_DETAILS_DATA_SEARCH_ASSIGNMENT_DETAILS_DATA_TO_SEND_NOTIF("assignmentDetailData_searchAssignmentDetailsDataToSendNotif"),
    ASSIGNMENT_DETAILS_DATA_SEARCH_ASSIGNMENT_PREV_DETAILS_DATE("assignmentDetailData_searchAssignmentPrevDetailsData"),
    /******************************************************************************************************************/
    ASSIGNMENT_AGENT_CODE_SEARCH_ASSIGNMENT_AGENT_CODE("assignmentAgentCode_searchAssignmentAgentCode"),
    REGION_DEPARTMENTS_SEARCH_REGION_DEPARTMENT_ID("regionDepartments_searchdRegionDepartmentsIds"),
    /******************************************************************************************************************/
    ASSIGNMENT_EVALUATION_SEARCH_ASSIGNMENT_EVALUATION("assignmentEvaluation_searchAssignmentEvaluation"),
    ASSIGNMENT_EVALUATION_ASSIGNMENT_EVALUATION_WF_INSTANCES("assignmentEvaluation_searchAssignmentEvaluationWFInstances"),
    /******************************************************************************************************************/
    ASSIGNMENT_EVALUATION_POINT_DATA_SEARCH_ASSIGNMENT_EVALUATION_POINT("assignmentEvaluationPointData_searchAssignmentEvaluationPoint"),
    ASSIGNMENT_EVALUATION_POINT_DATA_HAS_ASSIGNMENT_EVALUATION_POINT("assignmentEvaluationPointData_hasAssignmentEvaluationPoint"),
    /******************************************************************************************************************/
    ATTACHMENT_SEARCH_ATTACHMENT("attachment_searchAttachment"),
    /******************************************************************************************************************/
     BANK_BRANCH_DATA("bankBranchData_searchBankBranches"),    
    /******************************************************************************************************************/
    MENU_DATA_GET_EMP_MENUS("menuData_getEmployeeMenus"),
    MENU_DATA_GET_EMP_MENUS_BY_MENU_FLAG("menuData_getEmployeeMenusByMenuFlag"),
    /******************************************************************************************************************/
    USER_MENU_ACTION_CHECK_EMPLOYEE_MENU_ACTION("userMenuActionData_checkEmployeeMenuAction"),
    USER_MITOKEN_DATA_CHECK_USER_MITOKEN_DATA("userMiTokenData_checkUserMiTokenData"),
    /******************************************************************************************************************/
    LEG_INSTANCE_GET_INSTANCE_BY_ID("legInstance_getInstanceById"),
    /******************************************************************************************************************/
    ENTITY_SEQUENCE_GENERATOR_SEARCH_SEQUENCE_GENERATOR("entitySequenceGenerator_searchSequenceGenerator"),
    /******************************************************************************************************************/
    EMPLOYEE_DATA_SEARCH_EMPLOYEE("employeeData_searchEmployee"),
    EMPLOYEE_DATA_SEARCH_INFO_RELATED_EMPLOYEES("employeeData_searchInfoRelatedEmployees"),
    EMPLOYEE_DATA_SEARCH_EMPLOYEE_BY_REGION_ID("employeeData_searchEmployeeByRegionId"),
    EMPLOYEE_DATA_SEARCH_EMPLOYEE_HAVING_ASSIGNMENT("employeeData_searchEmployeesHavingAssignment"),
    EMPLOYEE_DATA_SEARCH_EMPLOYEE_BY_REGION_HAVING_ASSIGNMENT("employeeData_searchEmployeesByRegionHavingAssignment"),
    EMPLOYEE_DATA_SEARCH_EMPLOYEE_BY_EMPLOYEE_ID_LIST("employeeData_searchEmployeesByEmployeeIdList"),
    /******************************************************************************************************************/
    EMPLOYEE_NON_EMPLOYEE_DETAILS_SEARCH_EMPLOYEE_NON_EMPLOYEE_DETAILS("employeeNonEmployeeDetail_searchEmployeeNonEmployeeDetail"),
    /******************************************************************************************************************/
    EMP_NON_EMP_REALTIVE_SEARCH_EMP_NON_EMP_RELATIVES("empNonEmpRelative_searchEmpNonEmpRelatives"),
    /******************************************************************************************************************/
    DEPARTMENT_DATA_SEARCH_DEPARTMENT("departmentData_searchDepartment"),
    DEPARTMENT_DATA_SEARCH_INFO_RELATED_DEPARTMENTS("departmentData_searchInfoRelatedDepartments"),
    DEPARTMENT_DATA_SEARCH_DEPARTMENT_BY_MULTIPLE_IDS("departmentData_searchDepartmentByMultipleIds"),
    DEPARTMENT_DATA_SEARCH_DEPARTMENT_BY_MULTIPLE_IDS_AND_NAME_AND_CODE("departmentData_searchDepartmentByMultipleIdsAndNameAndCode"),
    DEPARTMENT_DATA_SEARCH_ASSIGNMENT_DEPARTMENTS("departmentData_searchAssignmentDepartments"),
    /******************************************************************************************************************/
    DEPARTMENT_TITLE_DATA_SEARCH_DEPARTMENT_MANAGER("departmentTitleData_searchDepartmentManager"),
    /******************************************************************************************************************/
    DEPARTMENT_TYPE_DATA_SEARCH_DEPARTMENT_TYPE("departmentTypeData_searchDepartmentType"),
    /******************************************************************************************************************/
    DEPARTMENT_SECTOR_DATA_SEARCH_DEPARTMENT_SECTOR_DATA("departmentSectorData_searchDepartmentSectorData"),
    /******************************************************************************************************************/
    DEPARTMENT_HIER_DATA_SEARCH_DEPARTMENT_HIER("departmentHierData_searchDepartmentHier"),
    /******************************************************************************************************************/
    COUNTRY_DATA_SEARCH_COUNTRY("countryData_searchCountry"),
    COUNTRY_DATA_SEARCH_INFO_RELATED_COUNTRIES("countryData_searchInfoRelatedCountries"),
    /******************************************************************************************************************/
    IMAGE_GET_IMAGE("image_getImage"),
    /******************************************************************************************************************/
    INFO_TYPE_SEARCH_INFO_TYPES("infoType_searchInfoType"),
    /******************************************************************************************************************/
    INFO_DATA_SEARCH_INFO_WITH_RELATED_ENTITIES_AND_SOURCES("infoData_searchInfoWithRelatedEntitiesAndSources"),
    INFO_DATA_SEARCH_INFO_WITH_RELATED_ENTITIES("infoData_searchInfoWithRelatedEntities"),
    INFO_DATA_SEARCH_INFO_WITH_SOURCES("infoData_searchInfoWithSources"),
    INFO_DATA_SEARCH_INFO("infoData_searchInfo"),
    INFO_DATA_SEARCH_INFO_ASSIGNMENT("infoData_searchInfoAssignment"),
    INFO_DATA_SEARCH_INFO_OPEN_SOURCE("infoData_searchInfoOpenSource"), 
    INFO_DATA_SEARCH_INFO_RELATED_ENTITY("infoData_searchInfoRelatedEntity"),
    INFO_DATA_SEARCH_INFO_VISIBLE_DEPARTMENTS("infoData_searchInfoVisibleDepartments"),
    INFO_DATA_SEARCH_GET_INFO_BY_EMPLOYEE("infoData_getInfoByEmployee"),
    INFO_DATA_SEARCH_INFO_PHONE("infoData_searchInfoPhone"),
    INFO_DATA_COUNT_INFO_RELATED_ENTITY("infoData_countInfoRelatedEntity"),
    /******************************************************************************************************************/
    INFO_SUBJECT_SEARCH_INFO_SUBJECTS("infoSubject_searchInfoSubject"),
    /******************************************************************************************************************/
    INTEGRATION_EMPLOYEE_ACTIVITY_DATA_SEARCH_INTEGRATION_EMPLOYEE_ACTIVITY_DATE("integrationEmployeeActivityData_searchIntegrationEmployeeActivityData"),
    /******************************************************************************************************************/
    SECURITY_STATUS_USER_SEARCH_SECURITY_STATUS_USERS("SecurityStatusUser_searchSecurityStatusUsers"),
    /******************************************************************************************************************/
    QUALIFICATION_DATA_SEARCH_QUALIFICATION("qualificationData_searchQualification"),
    /******************************************************************************************************************/
    SECURITY_CHECK_NON_EMPLOYEE_DATA_SEARCH_SECURITY_CHECK_NON_EMPLOYEE("securityCheckNonEmployeeData_searchSecurityCheckNonEmployee"),
    /******************************************************************************************************************/
    SECURITY_CHECK_EMPLOYEE_DATA_SEARCH_SECURITY_CHECK_EMPLOYEE("securityCheckEmployeeData_searchSecurityCheckEmployee"),
    /******************************************************************************************************************/
    SECURITY_CHECK_PERSON_DELETE_SECURITY_CHECK_PERSON("SecurityCheckPerson_deleteSecurityCheckPerson"),
    /******************************************************************************************************************/
    SECURITY_CHECK_DATA_SEARCH_SECURITY_CHECK_BY_ID("securityCheckData_searchSecurityCheckById"),
    SECURITY_CHECK_DATA_SEARCH_SECURITY_CHECK_EMPLOYEE("securityCheckData_searchSecurityCheckEmployee"),
    SECURITY_CHECK_DATA_SEARCH_SECURITY_CHECK_NON_EMPLOYEE("securityCheckData_searchSecurityCheckNonEmployee"),
    SECURITY_CHECK_DATA_SEARCH_SECURITY_CHECK_BY_PERSON("securityCheckData_searchSecurityCheckByPerson"),
    SECURITY_CHECK_DATA_COUNT_SECURITY_CHECK("securityCheckData_countSecurityCheck"),
    /******************************************************************************************************************/
    LAB_CHECK_SEARCH_LAB_CHECK("labCheck_searchLabCheck"),
    LAB_CHECK_SEARCH_LAB_CHECK_DETAILS("labCheck_searchLabCheckDetails"),
    LAB_CHECK_SEARCH_LAB_CHECK_EMPLOYEE("labCheckEmployeeData_searchLabCheckEmployees"),
    LAB_CHECK_SEARCH_LAB_CHECK_EMPLOYEE_TO_RETEST("labCheckEmployeeData_searchLabCheckEmployeesToRetest"),
    LAB_CHECK_COUNT_LAB_CHECK_EMPLOYEE("labCheckEmployeeData_countLabCheckEmployees"),
    LAB_CHECK_EMPLOYEE_DATE_CHECK_EMPLOYEE_ACTION_STATUS("labCheckEmployeeData_checkEmployeeActionStatus"),
    LAB_CHECK_EMPLOYEE_DATE_VALIDATE_EMPLOYEE_LAB_CHECK("labCheckEmployeeData_validateEmployeeLabCheck"),
    LAB_CHECK_EMPLOYEE_DATE_VALIDATE_SAMPLE_NUMBER("labCheckEmployeeData_validateSampleNumber"),
    LAB_CHECK_COUNT_LAB_CHECK_EMPLOYEE_WITHIN_PERIOD("labCheckEmployeeData_countLabCheckEmployeesWithinPeriod"),
    LAB_CHECK_SEARCH_LAST_LAB_CHECK_EMPLOYEE_BY_CHECK_REASON("labCheckEmployeeData_searchLastLabCheckEmployeesByCheckReason"),
    LAB_CHECK_SEARCH_DELAYED_LAB_CHECK_EMPLOYEE("labCheckEmployeeData_searchDelayedLabCheckEmployees"),
    LAB_CHECK_SEARCH_LAB_CHECKS_AT_UNIT_FOR_EMPLOYEE("labCheckEmployeeData_searchLabChecksAtUnitForEmployees"),
    LAB_CHECK_SEARCH_LAB_CHECK_BY_WF_TASK_IDS("labCheck_searchLabCheckByWFTaskIds"),
    LAB_CHECK_EMPLOYEE_DATA_SEARCH_EMPLOYEE_LAB_CHECK_BY_SAMPLE_DATA("labCheckEmployeeData_searchEmployeeLabCheckBySampleData"),
    /******************************************************************************************************************/
    INFO_PHONE_DELETE_INFO_PHONES("infoPhone_deleteInfoPhones"),
    INFO_VISIBLE_DEPARTMENT_DELETE_INFO_VISIBLE_DEPARTMENTS("infoVisibleDepartment_deleteInfoVisibleDepartment"),
    INFO_SOURCE_DELETE_INFO_SOURCES("infoSource_deleteInfoSource"),
    INFO_COORDINATE_DELETE_INFO_COORDINATES("infoCoordinate_deleteInfoCoordinates"),
    INFO_RELATED_ENTITY_DELETE_INFO_RELATED_ENTITIES("infoRelatedEntity_deleteInfoRelatedEntities"),
    /******************************************************************************************************************/
    NON_EMPLOYEE_SEARCH_NON_EMPLOYEE("nonEmployee_searchNonEmployee"),
    NON_EMPLOYEE_SEARCH_INFO_RELATED_NON_EMPLOYEES("nonEmployeeData_searchInfoRelatedNonEmployees"),
    NON_EMPLOYEE_PERMIT_SEARCH_NON_EMPLOYEE_PERMIT("nonEmployeePermit_searchNonEmployeePermit"),
    EMPLOYEE_NON_EMPLOYEE_ATTENDANCE_CAR_DATA_SEARCH_EMPLOYEE_NON_EMPLOYEE_ATTENDENCE_DATA("employeeNonEmployeeAttendanceCarData_searchEmployeeNonEmployeeAttendanceData"),
    EMPLOYEE_NON_EMPLOYEE_ATTENDANCE_CAR_DATA_SEARCH_EMPLOYEE_NON_EMPLOYEE_ATTENDENCE_CAR_DATA("employeeNonEmployeeAttendanceCarData_searchEmployeeNonEmployeeAttendanceCarData"),
    CAR_PERMIT_SEARCH_CAR_PERMIT("carPermit_searchCarPermit"),
    PERMITS_PATCH_DETAILS_SEARCH_PERMITS_PATCH_DETAILS("permitsPatchDetails_searchPermitsPatchDetails"),
    /******************************************************************************************************************/
    EMP_NON_EMP_CAR_PERMITS_DATA_SEARCH_EMP_NON_EMP_CAR_PERMITS_DATA("empNonEmpCarPermitsData_searchEmpNonEmpCarPermitsData"),
    /******************************************************************************************************************/
    NON_EMPLOYEE_DATA_SEARCH_NON_EMPLOYEE("nonEmployeeData_searchNonEmployee"),
    /******************************************************************************************************************/
    AUDIT_LOG_GET_LOG_BY_CONTENT("auditLog_getLogByUser"),
    /******************************************************************************************************************/
    INFO_SYS_CONFIG_GET_CONFIGURATIONS("infoSys_getConfigurations"),
    /******************************************************************************************************************/
    ELM_INTEG_CONFIG_DATA_GET_ELM_CONFIGURATIONS("elmIntegConfigData_getElmConfigurations"),
    /******************************************************************************************************************/
    SETUP_CLASS_SEARCH_CLASS("setupClass_searchClass"),
    /******************************************************************************************************************/
    SETUP_DOMAIN_SEARCH_DOMAIN("setupDomain_searchDomain"),
    SETUP_DOMAIN_SEARCH_INFO_RELATED_ENTITIES("setupDomain_searchInfoRelatedDomains"),
    /******************************************************************************************************************/
    RANK_DATA_SEARCH_RANK_BY_CATEGORY_ID("rankData_searchRankByCategoryId"),
    /******************************************************************************************************************/
    THREAD_GET_THREAD("thread_getThread"),
    /******************************************************************************************************************/
    CLASSIFICATION_TYPES_SEARCH_CLASSIFICATION_TYPES("classificationTypes_searchClassificationTypes"),
    /******************************************************************************************************************/
    CLASSIFICATION_SEARCH_CLASSIFICATION("classification_searchClassification"),
    /******************************************************************************************************************/
    INFO_SOURCE_SEARCH_INFO_SOURCE("infoSource_searchInfoSource"),
    /******************************************************************************************************************/
    INFO_RELATED_ENTITY_SEARCH_INFO_RELATED_ENTITY("infoRelatedEntity_searchInfoRelatedEntities"),
    /******************************************************************************************************************/
    INFO_RECOMMENDATION_DATA_SEARCH_INFO_RECOMMENDATIONS("infoRecommendationData_searchInfoRecommendations"),
    /******************************************************************************************************************/
    INFO_COORDINATE_SEARCH_INFO_COORDINATE("infoCoordinate_searchInfoCoordinates"),
    /******************************************************************************************************************/
    INFO_PHONE_SEARCH_INFO_PHONE("infoPhone_searchInfoPhones"),
    /******************************************************************************************************************/
    INFO_VISIBLE_DEPRATMENT_SEARCH_INFO_VISIBLE_DEPRATMENTS("infoVisibleDepartment_searchDepartmentData"),
    /******************************************************************************************************************/
    INFO_ANALYSIS_SEARCH_INFO_ANALYSIS("infoAnalysis_searchInfoAnalysis"),
    /******************************************************************************************************************/
    INFO_ANALYSIS_DETAIL_DATA_SEARCH_INFO_ANALYSIS_DETAILS("infoAnalysisDetailData_searchInfoAnalysisDetails"),
    INFO_ANALYSIS_REFERENCE_DATA_SEARCH_INFO_ANALYSIS_REFERENCES("infoAnalysisReferenceData_searchInfoAnalysisReferences"),
    /******************************************************************************************************************/
    OPEN_SOURCE_SEARCH_OPEN_SOURCE("openSource_searchOpenSource"),
    OPEN_SOURCE_SEARCH_INFO_OPEN_SOURCE("openSource_searchInfoOpenSource"),
    /******************************************************************************************************************/
    SURVEILLANCE_EMP_NON_EMP_DATA_SEARCH_SURVEILLANCE_EMP_NON_EMP_DATA("SurveillanceEmpNonEmpData_searchSurveillanceEmpNonEmpData"),
    SURVEILLANCE_EMP_NON_EMP_DATA_COUNT_SURVEILLANCE_EMP_NON_EMP_DATA("SurveillanceEmpNonEmpData_countSurveillanceEmpNonEmpData"),
    SURVEILLANCE_EMP_NON_EMP_DATA_GET_ACTIVE_SURVEILLANCE_EMP_NON_EMP_DATA("SurveillanceEmpNonEmpData_getActiveSurveillanceEmpNonEmpData"),
    /******************************************************************************************************************/
    SURVEILLANCE_ACTION_DATA_SEARCH_EMPLOYEE_SURVEILLANCE_ACTION("surveillanceActionData_searchEmployeeSurveillanceAction"),
    /******************************************************************************************************************/
    SURVEILLANCE_REPORT_SEARCH_EMPLOYEE_SURVEILLANCE_REPORT("surveillanceReport_searchEmployeeSurveillanceReport"),
    SURVEILLANCE_REPORT_SEARCH_EMPLOYEE_SURVEILLANCE_REPORT_FOR_APPROVED_ORDERS("surveillanceReport_searchEmployeeSurveillanceReportForApprovedOrders"),
    SURVEILLANCE_REPORT_DELETE_SURVEILLANCE_REPORT("surveillanceReport_deleteEmployeeSurveillanceReport"),
    /******************************************************************************************************************/
    SURVEILLANCE_REPORT_DETAIL_DATA_DELETE_SURVEILLANCE_REPORT_DETAIL("surveillanceReportDetailData_deleteSurveillanceReportDetail"),
    SURVEILLANCE_REPORT_DETAIL_DATA_SEARCH_SURVEILLANCE_REPORT_DETAIL("surveillanceReportDetailData_searchSurveillanceReportDetail"),
    /******************************************************************************************************************/
    SURVEILLANCE_ORDER_DATA_SEARCH_SURVEILLANCE_ORDER("surveillanceOrderData_searchSurveillanceOrder"),
    /******************************************************************************************************************/
    CAR_RENTAL_SEARCH_CAR_RENTALS("carRentalData_searchCarRentals"),
    /******************************************************************************************************************/
    EMPLOYEE_NON_EMPLOYEE_CARS_SEARCH_EMPLOYEE_NON_EMPLOYEE_CARS("employeeNonEmployeeCars_searchEmployeeNonEmployeeCars"),
    /******************************************************************************************************************/
    EMPLOYEE_NON_EMPLOYEE_ATTENDANCE_SEARCH_ATTENDENCE("employeeNonEmployeeAttendance_searchEmployeeNonEmployeeAttendance"),
    /******************************************************************************************************************/
    CAR_ATTENDENCE_DETAIL_SEARCH_CAR_ATTENDENCE_DETAILS("carAttendanceDetail_searchCarAttendanceDetail"),
    CAR_ATTENDENCE_DETAIL_DATA_SEARCH_CAR_ATTENDENCE_DETAILS("carAttendanceDetailData_searchCarAttendanceDetail"),
    /******************************************************************************************************************/
    VISITOR_ENTRANCE_DATA_SEARCH_VISITOR_ENTRANCE_DATA("visitorEntranceData_searchVisitorEntranceData"),
    /******************************************************************************************************************/
    MISSION_WEAPON_DATA_SEARCH_MISSION_WEAPON_DATA("missionWeaponData_searchMissionWeaponData"),
    /******************************************************************************************************************/
    MISSION_WEAPON_RECEIVE_ALL_MISSION_WEAPON("missionWeapon_receiveAllMissionWeapon"),
    MISSION_WEAPON_RETURN_ALL_MISSION_WEAPON("missionWeapon_returnAllMissionWeapon"),
    /******************************************************************************************************************/
    MISSION_CAR_RECEIVE_ALL_MISSION_CAR("missionCar_receiveAllMissionCar"),
    MISSION_CAR_RETURN_ALL_MISSION_CAR("missionCar_returnAllMissionCar"),
    /******************************************************************************************************************/
    MISSION_EQUIPMENT_RECEIVE_ALL_MISSION_EQUIPMENT("missionEquipment_receiveAllMissionEquipment"),
    MISSION_EQUIPMENT_RETURN_ALL_MISSION_EQUIPMENT("missionEquipment_returnAllMissionEquipment"),
    /******************************************************************************************************************/
    MISSION_CARS_SEARCH_MISSION_CAR_DATA("missionCarData_searchMissionCarData"),
    MISSION_CARS_COUNT_MISSION_CAR_DATA("missionCarData_countMissionCarData"),
    /******************************************************************************************************************/
    MISSION_EQUEPMENT_SEARCH_MISSION_EQUEPMENT_DATA("missionEquipmentData_searchMissionEquipmentData"),
    /******************************************************************************************************************/
    MISSION_GUARD_SEARCH_MISSION_GUARD("missionGuard_searchMissionGuard"),
    /******************************************************************************************************************/
    FIN_MONTHLY_REWARD_RESOURCE_DATA_SEARCH_FIN_MONTHLY_REWARDRE_SOURCE_DATA("finMonthlyRewardResourceData_searchFinMonthlyRewardResourceData"),
    FIN_MONTHLY_REWARD_SEARCH_FIN_MONTHLY_REWARD("finMonthlyReward_searchFinMonthlyReward"),
    FIN_MONTHLY_REW_DEP_DETAIL_SEARCH_FIN_MONTHLY_REW_DEP_DETAIL("finMonthlyRewDepDetail_searchFinMonthlyRewDepDetail"),
    FIN_YEAR_APPROVAL_SEARCH_FIN_YEAR_APPROVAL("FinYearApproval_searchFinYearApproval"),
    FIN_YEAR_APPROVAL_SEARCH_FIN_YEARS("FinYearApproval_searchFinYears"),
    FIN_INFO_REWARD_SUM_FIN_INFO_REWARD("finInfoReward_sumFinInfoReward"),
    FIN_INFO_REWARD_SEARCH_FIN_INFO_REWARD("finInfoReward_searchFinInfoReward"),
    /******************************************************************************************************************/
    FIN_YEAR_ACCOUNT_SUPPORT_SUM_FIN_YEAR_SUPPORT("finYearAccountSupport_sumFinYearSupport"),
    FIN_YEAR_ACCOUNT_SUPPORT_SEARCH_FIN_YEAR_SUPPORT("finYearAccountSupport_searchFinYearSupport"),
    /******************************************************************************************************************/
    FIN_MONTHLY_REW_DEP_DETAIL_SUM_FIN_MONTHLY_REWARD_TOTAL_SPENT("finMonthlyRewDepDetail_sumFinMonthlyRewardTotalSpent"),
    /******************************************************************************************************************/
    FIN_DEP_SUPPORT_DATA_SEARCH_FIN_DEP_SUPPORT_DATA("FinDepSupportData_searchFinDepSupportData"),
    /******************************************************************************************************************/
    PENALTY_ARREST_DATA_SEARCH("penaltyArrestData_searchPenaltyArrestData"),
    PENALTY_ARREST_DATA_VALIDATE_PENALTY_ARREST_DATA("penaltyArrestData_validatePenaltyArrestData"),
    /******************************************************************************************************************/
    FIN_DEP_SUPPORT_DETAIL_DATA_SUM_FIN_DEP_SUPPORT_AMOUNT("finDepSupportDetailData_sumFinDepSupportAmount"),
    FIN_DEP_SUPPORT_DETAIL_DATA_SEARCH_FIN_DEP_SUPPORT_DETAIL_DATA("finDepSupportDetailData_searchFinDepSupportDetailData"),
    FIN_DEP_SUPPORT_DETAIL_DATA_SEARCH_FIN_DEP_SUPPORT_DETAIL_DATA_BY_DEPARTMENT("finDepSupportDetailData_searchFinDepSupportDetailDataByDepartment"),
    /******************************************************************************************************************/
    LAB_CHECK_REPORT_EMPLOYEE_DATA_SEARCH_LAB_CHECK_REPORT_EMPLOYEE("labCheckReportEmployeeData_searchlabCheckReportEmployee"),
    /******************************************************************************************************************/
    LAB_CHECK_REPORT_SEARCH_LAB_CHECK_REPORT("labCheckReport_searchlabCheckReport"),
    /******************************************************************************************************************/
    LAB_CHECK_REPORT_DEPARTMENT_DATA_SEARCH_LAB_CHECK_REPORT_DEPARTMENT_DATA("labCheckReportDepartmentData_searchlabCheckReportDepartmentData"),
    /******************************************************************************************************************/
    LAB_CHECK_REPORT_DEPARTMENT_ACTION_SEARCH_LAB_CHECK_REPORT_DEPARTMENT_ACTION("labCheckReportDepartmentAction_searchlabCheckReportDepartmentAction"),
    /******************************************************************************************************************/
    LAB_CHECK_REPORT_DEPARTMENT_EMPLOYEE_DATA_SEARCH_LAB_CHECK_REPORT_DEPARTMENT_EMPLOYEE_DATA("labCheckReportDepartmentEmployeeData_searchlbChkRprtDptEmpData"),
    /******************************************************************************************************************/
    LAB_CHECK_REPORT_DATA_COUNT_LAB_CHECK_REPORTS_PER_ORDER_NUMBER("labCheckReportData_countLabCheckReportsPerOrderNumber"),
    /******************************************************************************************************************/
    FISHING_BOAT_OWNER_DATA_SEARCH_FISHING_BOAT_OWNERS("fishingBoatOwnerData_searchFishingBoatOwners"),
    FISHING_NAVIGATION_DATA_SEARCH_FISHING_NAVIGATIONS("fishingNavigationData_searchFishingNavigations"),
    FISHING_NAVIGATION_FOLLOWER_DATA_SEARCH_FISHING_NAVIGATION_FOLLOWERS("fishingNavigationFollowerData_searchFishingNavigationFollowers"),
    FISHING_NAVIGATION_SAILOR_DATE_SEARCH_FISHING_NAVIGATION_SAILORS("fishingNavigationSailorData_searchFishingNavigationSailors"),
    FISHING_NAVIGATION_DELEGATIONS_DATE_SEARCH_FISHING_NAVIGATION_DELEGATES("fishingNavigationDelegationData_searchFishingNavigationDelegates"),
    /******************************************************************************************************************/
	LETTER_DATA_SEARCH_LETTER_DATA("letterData_searchLetterData"),
    FOLLOW_UP_DATA_SEARCH_LAST_FOLLOW_UP_DATA("followUpData_searchLastFollowUpData"),
    FOLLOW_UP_RESULT_DATA_SEARCH_FOLLOW_UP_RESULT_DATA("followUpResultData_searchFollowUpResultData"),
    FOLLOW_UP_DATA_SEARCH_FOLLOW_UP_DATA("followUpData_searchFollowUpData"),
    FOLLOW_UP_DATA_CURRENT_FOLLOW_UP_DATA("followUpData_currentFollowUpData"),
    NETWORK_DATA_SEARCH_FOLLOW_UP_NETWORKS("networkData_searchFollowUpNetworks"),
    NETWORK_DATA_SEARCH_NETWORKS_SUMMARY("networkData_searchNetworksSummary"),
    NETWORK_DATA_SEARCH_NETWORKS("networkData_searchNetworks"),
    REGION_DATA_SEARCH_REGION_DATA("regionData_searchRegionData"),
    CONVERSATION_PARTY_DATA_SEARCH_CONVERSATION_PARTY_DATA("conversationPartyData_searchConversationPartyData"),
    REMINDER_DATA_SEARCH_REMINDERS("reminderData_searchReminders"),
    REFERRAL_DATA_SEARCH_REFERRALS("referralData_searchReferrals"), 
    GUIDANCE_REQUEST_DATA_SEARCH_GUIDANCE_REQUEST("guidanceRequestData_searchguidanceRequest"), 
    /******************************************************************************************************************/
    CONVERSATION_DATA_SEARCH_CONVERSATIONS("conversationData_searchConversations"), 
    CONVERSATION_DATA_SEARCH_CONVERSATION_DATA_LIST("conversationData_searchConversationDataList"), 
    /******************************************************************************************************************/
    WF_GET_WFINSTANCE_BY_ID("wf_instance_getWFInstanceById"),
    WF_COUNT_INSTANCES_BY_PROCESSES_IDS("wf_instance_countInstancesByProcessesIds"),

    WF_GET_WFINSTANCE_DATA_BY_ID("wf_instanceData_getWFInstanceDataById"),
    WF_SEARCH_WFINSTANCE_DATA("wf_instanceData_searchWFInstancesData"),
    WF_GET_WFINSTANCE_UNDER_PROCESSING_COUNT("wf_instanceData_getWFInstancesUnderProcessingCount"),
    WF_GET_WFINSTANCE_TASKS_DATA_SORTED("wf_taskData_getWFInstanceCompletedTasksDataSorted"),
    
    WF_GET_WFTASK_BY_ID("wf_task_getWFTaskById"),
    WF_GET_NEXT_NOTIFICATION("wf_task_getWFNextNotification"),
    WF_GET_NEXT_NOTIFICATION_RELATTIVE_TO("wf_task_getWFNextNotificationRelativeTo"),
    WF_GET_WFINSTANCE_TASKS("wf_task_getWFInstanceTasks"),
    WF_GET_WFINSTANCE_TASKS_DATA_SORTED_BY_TASK_ID("wf_taskData_getWFInstanceTasksDataSortedByTaskId"),
    WF_GET_WFINSTANCE_TASKS_BY_ROLE("wf_task_getWFInstanceTasksByRole"),
    WF_GET_WFINSTANCE_TASKS_BY_ROLE_LEVEL("wf_task_getWFInstanceTasksByRoleAndLevel"),
    WF_CAN_CHANGE_WFINSTANCE_DONE("wf_task_canChangeWFInstanceStatusToDone"),
    WF_CAN_CHANGE_WFINSTANCE_COMPLETE("wf_task_canChangeWFInstanceStatusToComplete"),
    WF_COUNT_TASKS("wf_task_countTasks"),
    WF_TASK_SECURITY("wf_task_taskSecurity"),
    WF_TASK_GET_WF_TASK_BY_TASK_IDS_LIST("wf_task_getWFTaskByTaskIdsList"),

    WF_GET_WFTASK_DATA_BY_ID("wf_taskData_getWFTaskDataById"),
    WF_SEARCH_WFTASK_DATA("wf_taskData_searchWFTasksData"),
    WF_GET_WFINSTANCE_TASKS_DATA("wf_taskData_getWFInstanceTasksData"),
    WF_GET_WFINSTANCE_COMPLETED_TASKS_DATA("wf_taskData_getWFInstanceCompletedTasksData"),

    WF_GET_PROCESSES_GROUPS("wf_group_getProcessesGroups"),
    WF_GET_PROCESSES_GROUPS_APRRROVAL_COUNTS("wf_group_getProcessesGroupsApprovalCounts"),

    WF_GET_GROUP_PROCESSES("wf_process_getGroupProcesses"),
    WF_GET_PROCESS("wf_process_getWFProcess"),

    WF_GET_DELEGATE("wf_delegation_getWFDelegation"),
    WF_GET_DELEGATIONS_COUNT("wf_delegation_getWFDelegationsCount"),
    WF_GET_DELEGATE_DATA("wf_delegationData_getWFDelegationData"),
    
    WF_GET_POSITION("wf_position_getWFPosition"),
    WF_GET_POSITION_BY_DESCRIPTION("wf_position_getWFPositionByDescription"),
    WF_POSITION_DATA_GET_WF_POSITION("wfPositionData_getWFPosition"),
    WF_POSITION_DATA_GET_WF_POSITION_FOR_TRANSFERED_EMPLOYEES("wfPositionData_getWFPositionForTransferedEmployees"),

    WF_GET_WFVACATION_BY_INSTANCE_ID("wf_vacation_getWFVacationByInstanceId"),
    WF_VALIDATE_VACATION_RUNNING_PROCESSES("wf_vacation_validateRunningProcesses"),
    WF_VALIDATE_VACATION_CHECK_DATES_CONFLICT("wf_vacation_checkDatesConflict"),
    WF_GET_WFVACATIONS_TASKS("wf_vacation_getVacationsTasks"),

    WF_GET_UNIT_RUNNING_WF_VACACTIONS_DATA("wf_vacationData_getUnitRunningWFVacationsData"),
    WF_COUNT_UNIT_RUNNING_WF_VACACTIONS_DATA("wf_vacationData_countUnitRunningWFVacationsData"),
    WF_GET_WF_DEF_LETTER_BY_INSTANCE_ID("hcm_WFDefLetter_getWFDefLetterByInstanceId"),
    WF_SEARCH_FISHING_NOTIFICATION_WFTASK_DATA("wf_taskData_searchWFFishingTasksData"),
    WF_TASK_DATA_GET_WF_TASK_IDS("wf_taskData_getWFTaskIds"),
    /******************************************************************************************************************/
    SETUP_SEARCH_LOCATION_PROFILE_DATA("locationProfile_searchLocation"), 
    WF_GET_WFTASKS_DATA_BY_INSTANCE_ID_AND_ASSIGNEE_ROLE("wf_taskData_getWFTaskDataByInstanceIdAndAssigneeRole"), 
    ;	    
    private String code;
      
    private QueryNamesEnum(String code){
        this.code = code;
    }
  
    public String getCode(){return code;}
}