package com.code.enums;

public enum ReportNamesEnum {
    LAB_CHECK("/LabCheck/LabCheck.jrxml"),
    LAB_CHECK_DETAILS("/LabCheck/LabCheckDetails.jrxml"),
    LAB_CHECK_EMPLOYEE_DETAILS("/LabCheck/EmployeeLabCheckDetails.jrxml"),
    CAR_RENTAL_STATISTICS("/CarRental/ReportStatistics.jrxml"),
    LAB_CHECK_MISSION_REPORT("/LabCheck/LabCheckMission.jrxml"),
    LAB_CHECK_MISSION_REPORT_DETAILS("/LabCheck/MissionReport.jrxml"),
    LAB_CHECK_BY_ORDER_NUMBER_AND_ORDER_DATE("/LabCheck/LabCheckBasedOnOrderNoReport.jrxml"),
    PROMOTIONS_ELIGIBLE_ALL_EMP_REPORT("/LabCheck/PromEligibleAllEmpReport.jrxml"),
    PROMOTIONS_ELIGIBLE_EMP_WITH_LAB_CHECK_REPORT("/LabCheck/PromEligibleEmpWithLabCheckReport.jrxml"),
    PROMOTIONS_ELIGIBLE_EMP_WITHOUT_LAB_CHECK_REPORT("/LabCheck/PromEligibleEmpWithoutLabCheckReport.jrxml"),
    PAST_LAB_CHECK_EMPLOYEE("/LabCheck/PastLabCheckEmployeeReport.jrxml"),
    CAR_RENTAL("/CarRental/CarRental.jrxml"),
    CAR_RENTAL_REGISTRATION("/CarRental/CarRentalRegistration.jrxml"),
    SECURITY_GUARD_MISSION("/SecurityMission/SecurityMission.jrxml"),
    SECURITY_GUARD_MISSION_DETAILS("/SecurityMission/SecurityMissionDetails.jrxml"),
    VISITORS_ENTRANCE("/SecurityMission/VisitorsEntrance.jrxml"),
    VISITORS_ENTRANCE_NO_EXIT("/SecurityMission/VisitorsEntranceNoExit.jrxml"),
    SECURITY_CHECK_EMP("/SecurityCheck/SecurityCheckEmp.jrxml"),
    SURVEILLANCE_EMPLOYEES("/Surveillance/SurveillanceEmployees.jrxml"),
    SURVEILLANCE_EMPLOYEES_STATISTICAL("/Surveillance/SurveillanceEmployeesStatistical.jrxml"),
    SURVEILLANCE_REPORT("/Surveillance/SurveillanceReport.jrxml"),
    SURVEILLANCE_ORDER("/Surveillance/SurveillanceOrder.jrxml"),
    SECURITY_CHECK_NON_EMP("/SecurityCheck/SecurityCheckNonEmp.jrxml"),
    SECURITY_CHECK_STATISTICAL_EMP("/SecurityCheck/SecurityCheckStatisticalEmp.jrxml"),
    SECURITY_CHECK_STATISTICAL_NON_EMP("/SecurityCheck/SecurityCheckStatisticalNonEmp.jrxml"),
    SECURITY_CHECK_REPLY_LETTER("/SecurityCheck/SecurityCheckReplyLetter.jrxml"),
    SECURITY_CHECK_DETAILS("/SecurityCheck/SecurityCheckDetails.jrxml"),
    EMPLOYEE_DETAILS("/SecurityCheck/EmployeeDetails/EmployeeDetails.jrxml"),
    NON_EMPLOYEE_DETAILS("/SecurityCheck/NonEmployeeDetails/NonEmployeeDetails.jrxml"),
    NIGHT_ATTENDANCE("/SecurityMission/NightAttendance.jrxml"),
    DEPARTMENT_ACCOUNT_SUPPORT("/Finance/DepartmentAccountSupport.jrxml"),
    DEPARTMENT_ACCOUNT_SUPPORT_STATISTICAL("/Finance/DepartmentAccountSupportStatistical.jrxml"),
    DEPARTMENT_ACCOUNT_SUPPORT_DETAILS("/Finance/DepartmentAccountSupportDetails.jrxml"),
    FINANCE_ACCOUNT_SUPPORT_REPORT("/Finance/FinanceAccountSupport.jrxml"),
    MONTHLY_REWARD_REPORT("/Finance/MonthlyReward.jrxml"),
    MONTHLY_REWARD_DETAILS("/Finance/MonthlyRewardDetails.jrxml"),
    MONTHLY_REWARD_STATISTICS_REPORT("/Finance/MonthlyRewardStatistics.jrxml"),
    MONTHLY_REWARD_REPORT_BY_IBAN("/Finance/MonthlyRewardByIBAN.jrxml"),
    MONTHLY_REWARD_REPORT_BY_CHEQUE("/Finance/MonthlyRewardByCheque.jrxml"),
    INFO_REWARD("/Finance/InformationRewardReport.jrxml"),
    INFO_REWARD_STATISTICAL("/Finance/InformationRewardReportStatistical.jrxml"),
    EMPLOYEE_ASSIGNMENT("/Assignment/EmployeeAssignmentReport.jrxml"),
    EMPLOYEE_ASSIGNMENT_STATISTICAL("/Assignment/EmployeeAssignmentReportStatistical.jrxml"),
    EMPLOYEE_ASSIGNMENT_REWARD_LETTER("/Assignment/ApprovedEmployeeAssignmentRewardReport.jrxml"),
    NONEMPLOYEE_ASSIGNMENT("/Assignment/NonemployeeAssignmentReport.jrxml"),
    NONEMPLOYEE_ASSIGNMENT_STATISTICAL("/Assignment/NonemployeeAssignmentReportStatistical.jrxml"),
    LABORATORY_TEST_REPORT("/LaboratoryTestReport/LaboratoryTestReport.jrxml"),
    LABORATORY_TEST_STATISTICS_REPORT("/LaboratoryTestStatisticsReport/LaboratoryTestStatisticsReport.jrxml"),
    LAB_CHECK_REPORT("/LabCheckSearch/LabCheckSearchReport.jrxml"),
    REGION_INFORMATION_REPORT("/Information/RegionInformationReport/RegionInformationReport.jrxml"),
    REGION_INFORMATION_STATISTICS_REPORT("/Information/RegionInformationReport/RegionInformationStatisticsReport.jrxml"),
    INFORMATION_ANALYSIS_REPORT("/Information/InformationAnalysisReport/InformationAnalysisReport.jrxml"),
    INFORMATION_ANALYSIS_STATISTICS_REPORT("/Information/InformationAnalysisReport/InformationAnalysisStatisticsReport.jrxml"),
    INFORMATION_INFO_TYPE_REPORT("/Information/InformationByInfoTypeReport/InformationByInfoTypeReport.jrxml"),
    INFORMATION_INFO_TYPE_STATISTICS_REPORT("/Information/InformationByInfoTypeReport/InformationByInfoTypeStatisticsReport.jrxml"),
    INFORMATION_INCOMMING_DOMAIN_REPORT("/Information/InformationByIncommingDomainReport/InformationByIncommingDomainReport.jrxml"),
    INFORMATION_INCOMMING_DOMAIN_STATISTICS_REPORT("/Information/InformationByIncommingDomainReport/InformationByIncommingDomainStatisticsReport.jrxml"),
    INFORMATION_DETAILS_REPORT("/Information/InformationDetailsReport/Information.jrxml"),
    INFORMATION_SEARCH_DETAIL("/Information/informationSearchDetail/InformationSearchDetail.jrxml"),
    NON_EMPLOYEE_RE_ASSIGNMENT_DETAIL("/Assignment/nonEmployeeReAssignmentDetail/nonEmployeeReAssignment.jrxml"),
    NON_EMPLOYEE_ASSIGNMENT_DETAIL("/Assignment/nonEmployeeAssignmentDetail/nonEmployeeAssignment.jrxml"),
    NON_EMPLOYEE_EVAL_RESUME("/AssignmentEvalution/nonEmployeeEvalResume/nonEmployeeEvalResume.jrxml"),
    NON_EMPLOYEE_EVAL_END("/AssignmentEvalution/nonEmployeeEvalEnd/nonEmployeeEvalEnd.jrxml"),
    EMPLOYEE_ASSIGNMENT_DETAIL("/Assignment/employeeAssignmentDetail/employeeAssignmentDetail.jrxml"),
    EMPLOYEE_RE_ASSIGNMENT_DETAIL("/Assignment/employeeReAssignmentDetail/employeeReAssignment.jrxml"),
    EMPLOYEE_EVAL_END("/AssignmentEvalution/employeeEvalEnd/employeeEvalEnd.jrxml"),
    EMPLOYEE_EVAL_RESUME("/AssignmentEvalution/employeeEvalResume/employeeEvalResume.jrxml"),
    FISHING_DETAILS_REPORT("/FishingReport/fishingDetailsReport.jrxml"),
    EXEMPTS_REPORT("/LabCheck/ExemptsReport.jrxml"),
    EMPLOYEE_ACTIVITIES_REPORT("/Surveillance/EmployeeActivities.jrxml"),
    NATIONAL_IDENTITY_SECURITY_STATUS("/SecurityAction/NationalIdentitySecurityStatus.jrxml"),
    RESIDENT_SECURITY_STATUS("/SecurityAction/ResidentSecurityStatus.jrxml"),
    VISIT_VISA_SECURITY_STATUS("/SecurityAction/VisitVisaSecurityStatus.jrxml"),
    KHALEEJI_IDENTITY_SECURITY_STATUS("/SecurityAction/KhaleejiIdentitySecurityStatus.jrxml"),
    KHALEEJI_PASSPORT_SECURITY_STATUS("/SecurityAction/KhaleejiPassportSecurityStatus.jrxml"),
    CAR_SECURITY_STATUS("/SecurityAction/CarSecurityStatus.jrxml"),
    SECURITY_GUARD_MISSION_SEARCH_DETAILS("/SecurityGuardMission/SecurityGuardMission.jrxml"),
    REVIEWING_SYSTEM_WORK_REPORT("/WorkStatus/reviewingSystemWorkReport.jrxml"),
    LAB_CHECK_STATS_FOR_REGIONS_REPORT("/LabCheckStatsReport/LabCheckStatsReport.jrxml"),
    LAB_CHECK_STATS_FOR_TRAINING_CENTERS_REPORT("/LabCheckStatsReport/LabCheckStatsReport.jrxml"),
    LAB_CHECK_STATS_BASED_ON_MATERIAL_TYPE_REPORT("/LabCheckStatsReport/PostiveCheckStatsBasedOnMaterialType.jrxml"),
    LAB_CHECK_STATS_BASED_ON_AGE_REPORT("/LabCheckStatsReport/PostiveCheckStatusBasedOnAge.jrxml"),
    LAB_CHECK_STATS_BASED_ON_OFFICER_RANKS_REPORT("/LabCheckStatsReport/PostiveCheckStatusBasedOnOfficersRanks.jrxml"),
    LAB_CHECK_STATS_BASED_ON_SOLDIER_RANKS_REPORT("/LabCheckStatsReport/PostiveCheckStatusBasedOnSoldiersRanks.jrxml"),
    LAB_CHECK_STATS_BASED_ON_OPERATIONAL_DEP_TYPE_REPORT("/LabCheckStatsReport/PostiveCheckStatusBasedOnMilitarySpeciality.jrxml"),
    LAB_CHECK_WF_TASKS_APPROVAL("/LabCheckWFTasksApproval/LabCheckWFTasksApproval.jrxml"),
    FOLLOW_UP_IN_DURATION("/SecurityAnalysis/FollowUp/FollowUpInDuration.jrxml"),
    FOLLOW_UP_IN_DURATION_STATISITICS("/SecurityAnalysis/FollowUp/FollowUpInDurationStatisitics.jrxml"),
    OBSERVED_GHOST_IN_DURATION("/SecurityAnalysis/FollowUp/ObservedGhostInDuration.jrxml"),
    DELAYED_GHOST_IN_DURATION("/SecurityAnalysis/FollowUp/DelayedGhostInDuration.jrxml"),
    REFERRAL_GHOST_IN_DURATION("/SecurityAnalysis/FollowUp/ReferralGhostInDuration.jrxml"),
    REFERRAL_GHOST_IN_DURATION_STATISITICS("/SecurityAnalysis/FollowUp/ReferralGhostInDurationStatisitics.jrxml"),
    CONVERSATION_DETAILS("/SecurityAnalysis/FollowUp/ConversationDetails.jrxml"),
    FOLLOW_UP_POSITIVE_RESULTS("/SecurityAnalysis/FollowUp/FollowUpPositiveResults.jrxml"),
    FOLLOW_UP_EXTENDED_NUMBERS_REPORT("/SecurityAnalysis/FollowUp/FollowUpExtendedNumbersReport.jrxml"),
    CONVERSATION_REFERRALS_REPORT("/SecurityAnalysis/Conversation/ConversationsReferralsReport.jrxml"),
    CONVERSATIONS_DURING_PERIOD_REPORT("/SecurityAnalysis/Conversation/ConversationsDuringPeriodReport.jrxml"),
    CONVERSATIONS_WITHIN_PERIOD_BASED_ON_CODE_REPORT("/SecurityAnalysis/Conversation/ConversationsWithinPeriod.jrxml"),
    DIRECT_FOLLOW_UPS("/SecurityAnalysis/FollowUp/DirectFollowsUps.jrxml"),
    
    ;
    
	private String code;

	private ReportNamesEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
