package com.code.enums;

public enum SessionAttributesEnum {
    CURRENT_LANG("CURRENT_LANG"),
    EMP_DATA("EMP_DATA"),
    USER_MENU("USER_MENU"),
    USER_MENU_TREE("USER_MENU_TREE"),
    USER_MENU_REPORT_TREE("USER_MENU_REPORT_TREE"),
    USER_MENU_WORKFLOW_TREE("USER_MENU_WORKFLOW_TREE"),
    FILE_ARCHIVING_PARAM("FILE_ARCHIVING_PARAM"),
    SECURITY_STATUS_SEARCH_FLAG("SECURITY_STATUS_SEARCH_FLAG"),
    SECURITY_STATUS_MANAGEMENT_FLAG("SECURITY_STATUS_MANAGEMENT_FLAG"),
    SECURITY_STATUS_ADMIN_MANAGEMENT_FLAG("SECURITY_STATUS_ADMIN_MANAGEMENT_FLAG");
	private String code;

	private SessionAttributesEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}

   