package com.code.enums;

public enum UserMenuActionsEnum {
	MILITARY_POLICE_DUTY_EMPLOYEE_DELIVER_EQUIPMENTS("MILITARY_POLICE_DUTY_EMPLOYEE_DELIVER_EQUIPMENTS"),
	CAR_MANAGEMENT_EMPLOYEE_DELIVER_CARS("CAR_MANAGEMENT_EMPLOYEE_DELIVER_CARS"),
	EMPLOYEE_ASSIGNMENT_EDIT("EMPLOYEE_ASSIGNMENT_EDIT"),
	NON_EMPLOYEE_ASSIGNMENT_EDIT("NON_EMPLOYEE_ASSIGNMENT_EDIT"),
	UPDATE_ATTENDANCE_CAR("UPDATE_ATTENDANCE_CAR"),
	LAB_CHECK_EDIT("LAB_CHECK_EDIT"),
	DELETE_ATTACHMENT_PERMISSION("DELETE_ATTACHMENT_PERMISSION")
	;

	private String code;
      
    private UserMenuActionsEnum(String code){
        this.code = code;
    }
    
    public String getCode(){return code;}
}
