package com.code.enums;

public enum WFProcessesEnum {
	NOTIFICATIONS(1),
	SURVEILLANCE_ORDER_REPORT(2),
	SURVEILLANCE_ORDER(3),
	EMPLOYEE_ASSIGNEMENT(4),
	INFORMATION(5),
	NON_EMPLOYEE_ASSIGNEMENT(6),
	SECURITY_GUARD_MISSION(7),
	SECURITY_CHECK(8),
	LAB_CHECK(9),
	EMPLOYEE_ASSIGNMENT_EVALUATION(10),
	NON_EMPLOYEE_ASSIGNMENT_EVALUATION(11),
	MONTHLY_REWARD(12),
	FINANCIAL_DEPARTMENT_SUPPORT(13),
	PENALTY_ARREST(14),
	FIHSING_AND_EXCURSIONS(15),
	CONVERSATION_GUIDANCE_REQUEST(16)
	;

	private long code;

	private WFProcessesEnum(long code) {
		this.code = code;
	}

	public long getCode() {
		return code;
	}

}
