
package com.code.integration.promotionsdrugstest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PromotionsDrugsTestWS", targetNamespace = "http://integration.code.com/promotionsDrugsTest")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PromotionsDrugsTestWS {


    /**
     * 
     * @param drugstestresults
     * @return
     *     returns com.code.integration.promotionsdrugstest.WsResponseBase
     */
    @WebMethod
    @WebResult(name = "promotionsDrugsTestResultsResponse", targetNamespace = "")
    @RequestWrapper(localName = "adjustPromotionsDrugsTestResults", targetNamespace = "http://integration.code.com/promotionsDrugsTest", className = "com.code.integration.promotionsdrugstest.AdjustPromotionsDrugsTestResults")
    @ResponseWrapper(localName = "adjustPromotionsDrugsTestResultsResponse", targetNamespace = "http://integration.code.com/promotionsDrugsTest", className = "com.code.integration.promotionsdrugstest.AdjustPromotionsDrugsTestResultsResponse")
    @Action(input = "http://integration.code.com/promotionsDrugsTest/PromotionsDrugsTestWS/adjustPromotionsDrugsTestResultsRequest", output = "http://integration.code.com/promotionsDrugsTest/PromotionsDrugsTestWS/adjustPromotionsDrugsTestResultsResponse")
    public WsResponseBase adjustPromotionsDrugsTestResults(
        @WebParam(name = "drugstestresults", targetNamespace = "")
        String drugstestresults);

}
